version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./upload:/upload  # Map the local upload directory to the container's /upload directory
    environment:
      - UPLOAD_PATH=/upload
